runtime: python311
env_variables:
  GEMINI_API_KEY: "AQ.Ab8RN6Jn5bQRSwhReMXLeDvLY7RTYVauQY3d8O8S5FI3VXUw-w"
  FIREBASE_PROJECT_ID: "stable-hydra-507904-h7"
  TWILIO_ACCOUNT_SID: "AC7ddf9a54347019e9f1eaeab343bf4f0b"
  TWILIO_AUTH_TOKEN: "b65724d6aebbc60ddb479801bfd7f8f7"
  TWILIO_WHATSAPP_NUMBER: "whatsapp:+14155238886"
  GOOGLE_APPLICATION_CREDENTIALS: "firebase-key.json"
